workflows:
    simulator-native-ios:
        name: iOS simulator build
        max_build_duration: 120
        environment:
            vars:
               XCODE_WORKSPACE: "your_workspace_name.xcworkspace" # <-- Put the name of your Xcode workspace here
               XCODE_SCHEME: "your_workspace_name" # <-- Put the name of your Xcode scheme here
            xcode: 13.0
            cocoapods: default
        scripts:
            - name: Install CocoaPods dependencies
              script: |
                                pod install
            - name: Build ipa for distribution
              script: |
                                xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.4' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 
        artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM